export default function Terms() {
  return (
    <>
      <section className="bg-brand-navy pt-20 pb-16">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h1 className="font-display text-4xl md:text-5xl text-white mb-4">Terms of Service</h1>
          <p className="font-body text-gray-300 text-lg max-w-2xl mx-auto">Terms and conditions for using Financials Studio</p>
        </div>
      </section>

      <section className="bg-white py-16 md:py-20">
        <div className="max-w-4xl mx-auto px-4">
          <p className="font-body text-gray-500 text-sm mb-10">Effective Date: 1 January 2025</p>

          <div className="space-y-10">
            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">1. Account Terms</h3>
              <p className="font-body text-gray-600 leading-relaxed mb-3">By creating an account with Financials Studio, you agree to the following:</p>
              <ul className="list-disc list-inside font-body text-gray-600 leading-relaxed space-y-1.5 ml-2">
                <li>You must be at least 18 years of age to use this service.</li>
                <li>You must provide accurate and complete information when creating your account.</li>
                <li>You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account.</li>
                <li>You must notify us immediately if you become aware of any unauthorised use of your account.</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">2. Generation Purchases</h3>
              <p className="font-body text-gray-600 leading-relaxed mb-3">Financials Studio operates on a pay-per-use model:</p>
              <ul className="list-disc list-inside font-body text-gray-600 leading-relaxed space-y-1.5 ml-2">
                <li>Each financial statement generation requires a purchased generation credit.</li>
                <li>Generation credits are non-refundable once a generation has been started.</li>
                <li>Unused generation credits do not expire and remain available in your account indefinitely.</li>
                <li>Prices for generation credits may change; any changes will be communicated in advance and will not affect previously purchased credits.</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">3. Acceptable Use</h3>
              <p className="font-body text-gray-600 leading-relaxed mb-3">You agree to use Financials Studio only for lawful purposes and in accordance with these terms:</p>
              <ul className="list-disc list-inside font-body text-gray-600 leading-relaxed space-y-1.5 ml-2">
                <li>You may only use the service for lawful financial reporting and accounting purposes.</li>
                <li>You may not attempt to reverse engineer, decompile, or disassemble any part of the software.</li>
                <li>You may not share your account credentials with any third party.</li>
                <li>You may not use the service to generate fraudulent or misleading financial documents.</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">4. Intellectual Property</h3>
              <p className="font-body text-gray-600 leading-relaxed">Financials Studio, including its design, features, and underlying technology, is the intellectual property of Client Focus Solutions. The financial statements generated by the service are subject to our intellectual property rights with respect to format and presentation. You retain full ownership of your financial data and the underlying figures contained in any generated documents.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">5. Limitation of Liability</h3>
              <p className="font-body text-gray-600 leading-relaxed mb-3">Financials Studio is provided on an "as is" basis:</p>
              <ul className="list-disc list-inside font-body text-gray-600 leading-relaxed space-y-1.5 ml-2">
                <li>We do not warrant that the service will be uninterrupted, error-free, or completely secure.</li>
                <li>We are not liable for any financial decisions made based on the outputs generated by Financials Studio.</li>
                <li>Users should verify all generated financial statements with a qualified chartered accountant before relying on them for statutory or regulatory purposes.</li>
                <li>In no event shall Client Focus Solutions be liable for any indirect, incidental, or consequential damages arising from the use of this service.</li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">6. Governing Law</h3>
              <p className="font-body text-gray-600 leading-relaxed">These Terms of Service shall be governed by and construed in accordance with the laws of the Republic of Zambia. Any disputes arising from or related to these terms shall be subject to the exclusive jurisdiction of the courts of Zambia.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">7. Changes to Terms</h3>
              <p className="font-body text-gray-600 leading-relaxed">We reserve the right to update or modify these Terms of Service at any time. When we make changes, we will notify registered users via email. Continued use of Financials Studio after changes have been communicated constitutes acceptance of the updated terms.</p>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-brand-charcoal mb-3">8. Contact</h3>
              <p className="font-body text-gray-600 leading-relaxed">If you have any questions about these Terms of Service, please contact us at <a href="mailto:legal@clientfocus.zm" className="text-brand-blue hover:underline">legal@clientfocus.zm</a>.</p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
